# Whatsapp group sentiment analysis
In this work I make a model to know the polarity of the sentiments of the messages in a whatsapp group.

In the development of the work I will analyse different aspects of the dynamics of the group, highlighting the activity of the different users, the type of messages and the topics that were discussed with their corresponding polarity.

this is my final work of the data analytic bootcamp, and i decided to do this work because i believe that the spontaneity and quantity of the messages are an extremely valuable resource to know the opinion of the people about relevant topics.

# 1.Get data

In [1]:
import pandas as pd
import re
from datetime import timedelta
from datetime import datetime

In [2]:
# Specify the path to your text file
file_path = 'WhatsApp.txt'

# Initialize lists to store parsed information
dates = []
times = []
senders = []
messages = []

# Define a regular expression pattern to extract information
pattern = re.compile(r'(\d+/\d+/\d+ \d+:\d+) - ([^:]+): (.+)')

# Open the file in read mode
with open(file_path, 'r', encoding='utf-8') as file:
    # Iterate through each line in the file
    for line in file:
        # Use the regular expression to match and extract information
        match = pattern.match(line.strip())
        if match:
            # Extract date, time, sender, and message
            datetime_str, sender, message = match.groups()

            # Convert date and time to a datetime object
            datetime_obj = datetime.strptime(datetime_str, '%d/%m/%y %H:%M')

            # Append information to the respective lists
            dates.append(datetime_obj.date())
            times.append(datetime_obj.time())
            senders.append(sender)
            messages.append(message)

# Create a DataFrame for easier analysis
df = pd.DataFrame({
    'Date': dates,
    'Time': times,
    'Sender': senders,
    'Message': messages
})

In [3]:
# Read the nickname mapping from CSV into a DataFrame
nickname_mapping = pd.read_csv('sender_nickname.csv')

# Create a mapping dictionary from 'Full Name' to 'Nickname'
name_mapping_dict = dict(zip(nickname_mapping['Full Name'], nickname_mapping['Nickname']))

# Replace values in the 'Sender' column of the original DataFrame (df) using the mapping
df['Sender'] = df['Sender'].replace(name_mapping_dict)

In [4]:
# Display the DataFrame
df.head()

         Date      Time Sender               Message
0  2021-02-02  01:29:00  Yames  <Multimedia omitido>
1  2021-02-02  04:04:00  Yames  <Multimedia omitido>
2  2021-02-02  04:05:00    Eze          Schames ü§¶‚Äç‚ôÇÔ∏è
3  2021-02-02  04:29:00  Delca        Jajajajajajaja
4  2021-02-02  04:30:00    Eze  <Multimedia omitido>

In [5]:
# Display the dataframe shape
df.shape

(39972, 4)

#  2.Data cleaning
## Cleaning Messages 
This step is critical in the sentiment analysis process - we need to make sure that the words and messages make sense to the model. It is about ensuring that the messages reach the sentiment analysis with meaning and do not cause confusion.
To achieve this, we need to clean the messages of jargon, including all kinds of onomatopoeias, emogis and multimedia so common in whatsapp communication. 
Stop words will be cleaned up later. They are not applicable at the moment because Bert Multilanguage needs them to interpret the messages.

In [6]:
# Create column to categorize MessageCount
msg_counts = df['Message'].value_counts().reset_index()
msg_counts.columns = ['Message','repetition']
msg_counts['repetition_cat'] = pd.cut(msg_counts['repetition'], bins=[0, 1, 2, 3, float('inf')],
                                       labels=['1 msg', '2 msg', '3 msg', '>3 msg'])

# Function to count words in a given text
def count_words(text):
    """
    Count the number of words in a given text.
    Parameters:
        text (str): The input text.
    Returns:
        int: The number of words in the text.
    """
    if isinstance(text, str):
        return len(text.split())
    else:
        return 0

# Apply the function to the 'text' column and create a new 'word_count' column
msg_counts['word_count'] = msg_counts['Message'].apply(lambda x: count_words(x))

msg_counts['word_count_cat'] = pd.cut(
    msg_counts['word_count'],
    bins=[0, 5, 10, float('inf')],
    labels=['1-4 words', '5-10 words', '>10 words']
)

msg_counts['word_count_group'] = pd.cut(
    msg_counts['word_count'],
    bins=[0, 10, float('inf')],
    labels=['short msg', 'regular msg']
)

In [7]:
# Create a pivot table with totals
result_pivot = pd.pivot_table(
    msg_counts, 
    index='repetition_cat', 
    columns=['word_count_group'], 
    values='repetition', 
    observed=False
)


result_pivot_filtered = result_pivot.loc[:, (result_pivot != 0).any(axis=0)]

# Display the filtered result_pivot
result_pivot_filtered

word_count_group  short msg  regular msg
repetition_cat
1 msg              1.000000          1.0
2 msg              2.000000          2.0
3 msg              3.000000          NaN
>3 msg            96.762162          NaN

In [8]:
# Create a pivot table with totals
result_pivot = pd.pivot_table(
    msg_counts,
    values='repetition',
    index='repetition_cat',
    columns=['word_count_cat'],
    aggfunc='sum',
    fill_value=0,
    margins=True,
    margins_name='Total',
    observed=False
)

result_pivot_filtered = result_pivot.loc[:, (result_pivot != 0).any(axis=0)]

# Display the filtered result_pivot
result_pivot_filtered

word_count_cat  1-4 words  5-10 words  >10 words  Total
repetition_cat
1 msg               11056        5665       4310  21031
2 msg                 708          14          6    728
3 msg                 312           0          0    312
>3 msg              17901           0          0  17901
Total               29977        5679       4316  39972

## Cleaning Messages | Short messages of 1 to 4 words

In [9]:
msg_counts[
    (msg_counts['word_count_cat']=='1-4 words') & 
    (msg_counts['repetition_cat'] !='1 msg')
].head(15)

,Message,repetition,repetition_cat,word_count,word_count_cat,word_count_group
0,<Multimedia omitido>,15400,>3 msg,2,1-4 words,short msg
1,Se elimin√≥ este mensaje.,275,>3 msg,4,1-4 words,short msg
2,Jajajaj,204,>3 msg,1,1-4 words,short msg
3,Jajaja,129,>3 msg,1,1-4 words,short msg
4,Jajajaja,89,>3 msg,1,1-4 words,short msg
5,ü§≠,60,>3 msg,1,1-4 words,short msg
6,Si,47,>3 msg,1,1-4 words,short msg
7,Schames,44,>3 msg,1,1-4 words,short msg
8,Cupelli,37,>3 msg,1,1-4 words,short msg
9,üëèüëèüëèüëè,37,>3 msg,1,1-4 words,short msg
10,Se√±ore,35,>3 msg,1,1-4 words,short msg
11,Jajajajaja,35,>3 msg,1,1-4 words,short msg
12,Schames...,32,>3 msg,1,1-4 words,short msg
13,üëèüëèüëè,29,>3 msg,1,1-4 words,short msg
14,null,29,>3 msg,1,1-4 words,short msg

Short messages have particular characteristics, they appear very often because they are brief and it is important to understand their nature given that most of them are short answers that have no meaning of their own, they are also used to make comments with double meaning (ironies) and also the use of signs or forms that are not understandable by the model.
* multimedia messages notes
* deleted messages notes
* slang or jargon
* use of marks and letters (alphabetic characters) to write onomatopoeias (Jajajaja, Jajaj, etc...)
* words with double meanings.
* emogis on the other hand has to be analysed separately
* null

## Cleaning Messages | Replace notes

In [10]:
def clean_msg_to_replace(text, elements_to_replace):
    if isinstance(text, str):
        for element in elements_to_replace:
            text = text.replace(element, '')
        return text.strip().lower()
    else:
        return text
    
message_to_replace = [
    ('<Multimedia omitido>'),
    ('Se elimin√≥ este mensaje.'),
    ('ubicaci√≥n en tiempo real compartida'),
    ('Eliminaste este mensaje.'),
    ('null'),
    ('\n'),
]

# Apply the clean_words_to_replace function to the 'Message' column
df['clean_msg'] = df['Message'].apply(lambda x: clean_msg_to_replace(x, message_to_replace))

In [11]:
df['clean_msg'].value_counts().head(15)

clean_msg
              15741
jajajaj         210
jajaja          157
jajajaja        103
ü§≠                60
si               48
jajajajaja       47
schames          45
cupelli          37
üëèüëèüëèüëè             37
se√±ore           35
jaja             35
schames...       32
üëèüëèüëè              29
cupelli...       28
Name: count, dtype: int64

## Cleaning Messages | Replace emoticons and onomatopoeias

In [12]:
def apply_regex_patterns(text, regex_patterns):
    if isinstance(text, str):
        for pattern, replacement in regex_patterns:
            text = re.sub(pattern, replacement, text)
        return text
    else:
        return text
    
# List of regex patterns and replacements
words_to_replace = [
    (r'[^\w\s]|_', ''),          # Replace everything that is not an alphabetical string, including emojis
    (r'http\S+', ''),            # Remove URLs
    (r'[0-9]+',''),               # Remove numbers
    (r'\s+', ' '),               # Replace multiple whitespaces with a single space
    (r'^\d+$',''),               # Replace strings consisting entirely of digits
    (r'([a-zA-Z])\1\1', '\\1'),  # Replace consecutive identical characters with a single character
]

# List of regex patterns and replacements
other_words_to_replace = [
    (r'\!{2,}', '!'),            # Replace repetition of !!! with !
    (r'\!', ''),                 # Remove !
    (r'\?{2,}', '?'),            # Replace repetition of ??? with ?
    (r'\.{2,}', ''),             # Remove repetition of ...
    (r'^\?\s*$', ''),            # Remove ? to treate it as emoji
    (r'^\!\s*$', ''),            # Remove ! to treate it as emoji
    (r'^:\-\)$', ''),            # Remove :-) to treate it as emoji
    (r'^;\-\)$', ''),            # Remove ;-) to treate it as emoji
    (r'\b(?:j[aj]*a[aj]*j[aj]*|ja(?:j[aj]*a[aj]*)*|ja(?:j[ak]*a[aj]*)*|ja+)\b', ''),  # Remove repetition of ja = :)
    (r'\b(?:j[ej]*e[ej]*j[ej]*|je(?:j[ej]*e[ej]*)*)\b', ''),                          # Remove repetition of je = :)
    (r'\b(?:j[oj]*o[oj]*j[oj]*|jo(?:j[oj]*o[oj]*)*|jo(?:j[ok]*o[oj]*)*|jo+)\b', ''),  # Remove repetition of jo = :)
    (r'\b(?:j[uj]*u[uj]*j[uj]*|ju(?:j[uj]*u[uj]*)*|ju(?:j[uk]*u[uj]*)*|ju+)\b', ''),  # Remove repetition of ju = :)
    (r'\b(jiji|jijij)\b', ''),                                                        # Remove repetition of ji = :) 
]

# Apply the function to the 'clean_msg' column
df['clean_msg'] = df['clean_msg'].apply(lambda x: apply_regex_patterns(x, words_to_replace))
df['clean_msg'] = df['clean_msg'].apply(lambda x: apply_regex_patterns(x, other_words_to_replace))

In [13]:
df['clean_msg'].value_counts().head(15)

clean_msg
                18366
schames            96
cupelli            70
si                 54
se√±ore             35
no                 33
feliz cumple       32
loras              31
muy bueno          30
loro               27
gracias            27
                   26
exacto             24
inadi              19
totalmente         18
Name: count, dtype: int64

## Cleaning Messages | Replace short messages with doble meaning
At this point I reemploy the short messages with double meanings by a phrase that replaces the real meaning of the message

In [14]:
def apply_patterns(series, patterns):
    for pattern, replacement in patterns:
        series = series.str.replace(pattern, replacement, regex=True, flags=re.IGNORECASE)
    return series

word_replacements = pd.read_csv('word_replacements.csv')
word_replacements_list = list(zip(word_replacements['Pattern'], word_replacements['Replacement']))

cleaned_replacements_list = [
    (rf'^\s*{str(pattern).replace("nan", "")}\s*$', rf'{str(replacement).replace("nan", "")}')
    for pattern, replacement in word_replacements_list
]

df['clean_msg'] = apply_patterns(df['clean_msg'], cleaned_replacements_list)

In [15]:
df['clean_msg'].value_counts().head(15)

clean_msg
                       18475
(risa)                   435
estoy de acuerdo         175
me gust√≥ eso             166
me sorprende             158
confirmo que si           91
si                        79
no estoy de acuerdo       67
no me gusta eso           58
confirmo que no           51
gracias                   38
feliz cumple              32
me gusta eso              28
                          26
y si                      15
Name: count, dtype: int64

## Cleaning Messages | Replace other words and marks

In [16]:
def apply_replacements(df, patterns):
    for pattern, replacement in patterns:
        df['clean_msg'] = df['clean_msg'].str.replace(pattern, replacement, regex=True, flags=re.IGNORECASE)

# Define your replacement patterns
replacement_patterns = [
    (r'^Bata\s+\w+$', '(risa)'),
    (r'^Basta\s+\w+$', '(risa)'),
    (r'^y( si)+$', 'confirmo que si'),
    (r'\b(gracias)+\b', 'gracias'),
    (r'\bgracias+\b', 'gracias'),
    (r'^Ok\.?\s*$', 'estoy de acuerdo'),
    (r'^se+\s*$', 'estoy de acuerdo'),
    (r'^Nah+\s*$', 'me sorprende'),
    (r'^No+\s*$', 'me sorprende'),
    (r'^\s*a+migos\s*$', 'amigos'),
    (r'^\s*([a-zA-Z])\s*$', ''),
    (r'^@\d+$', ''),
    (r'^\s+$', ''),
    (r'^\s*', ''),
    (r'^\s*si\b(?: si)+\s*$', 'confirmo que si'),
    (r'^(no\s)+no$', 'confirmo que no'),
    (r'b*chiques\b', 'amigos'),
    (r'b*o estoy crazy macaya\b', ''),
    (r'b*no es joda\b', 'hablo enserio'),
    (r'\b(Perdon)+\b', 'perd√≥n'),
    (r'\b(cumple+)+\b', 'cumplea√±os'),    
    (r'\b(ojo+)+\b', ''),
    (r'\b(epa+)+\b', ''),
    (r'\b(apa+)+\b', ''),
]    

# Apply replacements using the function
apply_replacements(df, replacement_patterns)

In [17]:
df['clean_msg'].value_counts().head(15)

clean_msg
                       18541
(risa)                   471
estoy de acuerdo         207
me sorprende             186
me gust√≥ eso             166
confirmo que si          121
si                        79
no estoy de acuerdo       67
no me gusta eso           58
confirmo que no           55
feliz cumplea√±os          51
gracias                   38
me gusta eso              28
perd√≥n                    20
muchas gracias            11
Name: count, dtype: int64

## Cleaning Messages | Short messages of 5 to 10 words

In [18]:
msg_counts[
    (msg_counts['word_count_cat']=='5-10 words') & 
    (msg_counts['repetition_cat'] !='1 msg')
].head(10)

,Message,repetition,repetition_cat,word_count,word_count_cat,word_count_group
302,Feliz cumple Santi !!! Abrazo grande!!!,2,2 msg,6,5-10 words,short msg
399,"Schames, no borres tus mensajes, dec√≠ lo que p...",2,2 msg,9,5-10 words,short msg
406,Segal no se haga el gracioso,2,2 msg,6,5-10 words,short msg
444,"Ok, lo qu√© hay que saber:",2,2 msg,6,5-10 words,short msg
477,"Puede ser exactamente es verdad, o tambi√©n tod...",2,2 msg,10,5-10 words,short msg
528,Alguien que le avise a Luis,2,2 msg,6,5-10 words,short msg
573,No se haga el gracioso Segal,2,2 msg,6,5-10 words,short msg

In this category of short messages (5-7 words) have a clear meaning and do not need modification, the repetitions are due to the fact that they are common ways of communicating. The use of multiple exclamation marks for emphasis is also observed.

## Cleaning Messages | Messages longer than 10 words
As we could see in the pivot table at the beginning, there are messages of normal size that are duplicated. We can then confirm that these are duplicate messages, other than short messages...

In [19]:
msg_counts[
    (msg_counts['word_count_cat']=='>10 words') & 
    (msg_counts['repetition_cat'] =='2 msg')
].head(15)

,Message,repetition,repetition_cat,word_count,word_count_cat,word_count_group
501,"Muchachos, debo dejar el grupo por problemas p...",2,2 msg,74,>10 words,regular msg
550,Los nuevos rufianes kirchneristas: DANIEL VILA...,2,2 msg,108,>10 words,regular msg
609,Totalmente negro. Sabias palabras. Una forma d...,2,2 msg,24,>10 words,regular msg

These are normal sized messages, so there is no reason why the messages would be duplicates.
This will most likely happen when messages are forwarded. This duplicate should be removed.

## Cleaning Messages | Drop regular messages duplicates

In [20]:
df['word_count'] = df['Message'].apply(lambda x: count_words(x))

# Creating word_count_group column based on word_count
df['word_count_group'] = pd.cut(
    df['word_count'],
    bins=[0, 7, float('inf')],
    labels=['short msg', 'regular msg']
)

df[(df.duplicated(subset=['Message'], keep=False)) & (df['word_count_group'] == 'regular msg')]

,Date,Time,Sender,Message,clean_msg,word_count,word_count_group
3114,2021-04-11,19:13:00,Garcia,"Muchachos, debo dejar el grupo por problemas p...",muchachos debo dejar el grupo por problemas pe...,74,regular msg
3671,2021-04-16,18:37:00,Javo,"Muchachos, debo dejar el grupo por problemas p...",muchachos debo dejar el grupo por problemas pe...,74,regular msg
7251,2021-06-18,15:53:00,Matias,"Puede ser exactamente es verdad, o tambi√©n tod...",puede ser exactamente es verdad o tambi√©n todo...,10,regular msg
7411,2021-06-20,02:50:00,Matias,"Puede ser exactamente es verdad, o tambi√©n tod...",puede ser exactamente es verdad o tambi√©n todo...,10,regular msg
8010,2021-06-29,21:26:00,Loro,Los nuevos rufianes kirchneristas: DANIEL VILA...,los nuevos rufianes kirchneristas daniel vila ...,108,regular msg
11127,2021-08-24,21:51:00,Juan,Totalmente negro. Sabias palabras. Una forma d...,totalmente negro sabias palabras una forma de ...,24,regular msg
11129,2021-08-24,21:54:00,Eze,Totalmente negro. Sabias palabras. Una forma d...,totalmente negro sabias palabras una forma de ...,24,regular msg
11794,2021-09-07,14:14:00,Barde,Los nuevos rufianes kirchneristas: DANIEL VILA...,los nuevos rufianes kirchneristas daniel vila ...,108,regular msg
26093,2023-02-20,17:06:00,Fede,"Schames, no borres tus mensajes, dec√≠ lo que p...",schames no borres tus mensajes dec√≠ lo que pensas,9,regular msg
26098,2023-02-20,18:46:00,Eze,"Schames, no borres tus mensajes, dec√≠ lo que p...",schames no borres tus mensajes dec√≠ lo que pensas,9,regular msg

In [21]:
regular_msg_subset = df[df['word_count_group'] == 'regular msg'].copy()
regular_msg_subset.drop_duplicates(subset=['Message'], keep='first', inplace=True)
df.loc[df['word_count_group'] == 'regular msg'] = regular_msg_subset

In [22]:
regular_msg_condition = (df['word_count_group'] == 'regular msg') & df['Message'].str.contains(
    'Los nuevos rufianes kirchneristas: DANIEL VILA...|'
    'Totalmente negro. Sabias palabras. Una forma d...|'
    'Muchachos, debo dejar el grupo por problemas p...',
    case=False
)

df[['Date', 'Time', 'Sender', 'Message', 'clean_msg']][regular_msg_condition]

,Date,Time,Sender,Message,clean_msg
3114,2021-04-11,19:13:00,Garcia,"Muchachos, debo dejar el grupo por problemas p...",muchachos debo dejar el grupo por problemas pe...
8010,2021-06-29,21:26:00,Loro,Los nuevos rufianes kirchneristas: DANIEL VILA...,los nuevos rufianes kirchneristas daniel vila ...
11127,2021-08-24,21:51:00,Juan,Totalmente negro. Sabias palabras. Una forma d...,totalmente negro sabias palabras una forma de ...

# 3.Feature engineering

## Message engineering | Spliting emojis from messages

In [23]:
Emoticon_to_replace = [
    (r'^\?\s*$', '‚ùì'),          # Replace ? with emoji
    (r'^\!\s*$', '‚ùó'),          # Replace ! with emoji
    (r'^:\-\)$', 'üòÇ'),          # Replace :-) with emoji
    (r'^;\-\)$', 'üòâ'),          # Replace ;-) with emoji

    (r'\b(ojo+)+\b', '‚ö†Ô∏è'),      # Replace comment with emoji
    (r'\b(epa+)+\b', '‚ö†Ô∏è'),      # Replace comment with emoji
    (r'\b(apa+)+\b', '‚ö†Ô∏è'),      # Replace comment with emoji

    (r'\b(?:j[aj]*a[aj]*j[aj]*|ja(?:j[aj]*a[aj]*)*|ja(?:j[ak]*a[aj]*)*|ja+)\b', 'üòÇ'),  # Replace jajaja with emoji
    (r'\b(?:j[ej]*e[ej]*j[ej]*|je(?:j[ej]*e[ej]*)*)\b', 'üòÇ'),                          # Replace jejeje with emoji
    (r'\b(?:j[oj]*o[oj]*j[oj]*|jo(?:j[oj]*o[oj]*)*|jo(?:j[ok]*o[oj]*)*|jo+)\b', 'üòÇ'),  # Replace jojojo with emoji
    (r'\b(?:j[uj]*u[uj]*j[uj]*|ju(?:j[uj]*u[uj]*)*|ju(?:j[uk]*u[uj]*)*|ju+)\b', 'üòÇ'),  # Replace jujuju with emoji
    (r'\b(jiji|jijij)\b', 'üòÇ'),                                                        # Replace jijiji with emoji
]

# Apply the function to the 'Message' column 
df['Message'] = df['Message'].apply(lambda x: apply_regex_patterns(x, Emoticon_to_replace))

In [24]:
import emoji

# Emoji extraction
df['emoji'] = df['Message'].apply(lambda x: ''.join(c for c in str(x) if c in emoji.EMOJI_DATA))

In [25]:
df['emoji'].value_counts().iloc[0:10]

emoji
          36757
üòÇ           362
ü§∑üèª‚ôÇ         200
ü§¶üèª‚ôÇ         101
ü§≠            65
ü§î            61
ü§™            56
ü§∑üèª‚ôÇü§¶üèª‚ôÇ       49
‚ö†            48
üòâ            47
Name: count, dtype: int64

In [26]:
# remove ‚ôÇ and replace ‚ö† with ‚ö†Ô∏è from emoji column
filtered_df = df[df['emoji'].str.contains(r'‚ôÇ', case=False, regex=True)]
df['emoji'] = df['emoji'].str.replace(r'‚ôÇ', '', regex=True, flags=re.IGNORECASE)
df['emoji'] = df['emoji'].str.replace(r'‚ö†', '‚ö†Ô∏è', regex=True, flags=re.IGNORECASE)
df['emoji'].value_counts().head(10)

emoji
        36757
üòÇ         362
ü§∑üèª        200
ü§¶üèª        106
ü§≠          65
ü§î          61
ü§™          56
ü§∑üèªü§¶üèª       49
‚ö†Ô∏è         48
üòâ          47
Name: count, dtype: int64

## Message engineering | Dropping empty messages
So far I have only replaced wrong or meaningless values by '', in this last step I filter out all the "" and delete the rows. Then I do the same with the null values.

In [27]:
# check null values on both columns (clean_msg and emoji)
df[(df['clean_msg'] == '') & (df['emoji'] == '')].shape

(17457, 8)

In [28]:
# Create a mask for rows where both 'clean_msg' and 'emoji' are empty
mask = (df['clean_msg'] == '') & (df['emoji'] == '')

# Drop the rows that meet the condition
df_filtered = df[~mask]
df.drop(df[mask].index, inplace=True)

In [29]:
# check null values
df.isnull().sum()

Date                5
Time                5
Sender              5
Message             5
clean_msg           5
word_count          5
word_count_group    5
emoji               0
dtype: int64

In [30]:
# drop rows with null values
df.dropna(subset=['clean_msg'], inplace=True)

In [31]:
df['clean_msg'].value_counts().head()

clean_msg
                    1084
(risa)               471
estoy de acuerdo     207
me sorprende         186
me gust√≥ eso         166
Name: count, dtype: int64

In [32]:
df['emoji'].value_counts().head(15)

emoji
        19295
üòÇ         362
ü§∑üèª        200
ü§¶üèª        106
ü§≠          65
ü§î          61
ü§™          56
ü§∑üèªü§¶üèª       49
‚ö†Ô∏è         48
üòâ          47
üëèüëèüëè        45
üëèüëèüëèüëè       41
ü§¶          39
ü§£ü§£ü§£        32
üò≥          32
Name: count, dtype: int64

In [33]:
# Replace remaining 1084 '' in column Clean_msg and 19295 in column Emoji
white_space_to_replace = [(r'^\s*$', '_')]   

# Apply the function to the 'Message' column 
df['emoji'] = df['emoji'].apply(lambda x: apply_regex_patterns(x, white_space_to_replace)) 
df['clean_msg'] = df['clean_msg'].apply(lambda x: apply_regex_patterns(x, white_space_to_replace))

## Date engineering | Date format and extraction of year, month and day of week
At this point, I modify the date format because I need to filter messages by date, as my plan is to analyse from 01/2022 onwards.

In [34]:
# Add a new column 'rDate' with the datetime values
df['rDate'] = pd.to_datetime(df['Date'])

# Extract month, year, and weekday information
df['Month'] = df['rDate'].dt.month
df['Year'] = df['rDate'].dt.year
df['Weekday'] = df['rDate'].dt.day_name()

# Handle missing values in 'Month'
df['Month'] = df['Month'].fillna(-1)  # Replace NaN with -1 or any suitable value
df['Month'] = df['Month'].astype(int)

# Handle missing values in 'Year' (if needed)
df['Year'] = df['Year'].fillna(-1)  # Replace NaN with -1 or any suitable value
df['Year'] = df['Year'].astype(int)

# Display the updated DataFrame
selected_columns = ['rDate', 'Month', 'Year', 'Weekday', 'Time', 'Sender', 'clean_msg', 'emoji', 'word_count_group']
df = df[selected_columns]
df.head()

,rDate,Month,Year,Weekday,Time,Sender,clean_msg,emoji,word_count_group
2,2021-02-02,2,2021,Tuesday,04:05:00,Eze,(risa),ü§¶,short msg
5,2021-02-02,2,2021,Tuesday,04:34:00,Barde,(risa),_,short msg
6,2021-02-02,2,2021,Tuesday,07:25:00,Juan,finoli finoli,_,short msg
7,2021-02-02,2,2021,Tuesday,07:25:00,Juan,tiene una amonestaci√≥n colectiva schames,_,short msg
11,2021-02-02,2,2021,Tuesday,12:41:00,Matias,me gust√≥ eso,_,short msg

##  Time engineering | Split Time to get Daytime

In [35]:
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.time

# Create new columns for morning, afternoon, and night
df['Morning'] = ((df['Time'].apply(lambda x: x.hour) >= 6) & (df['Time'].apply(lambda x: x.hour) < 13)).astype(int)
df['Afternoon'] = ((df['Time'].apply(lambda x: x.hour) >= 13) & (df['Time'].apply(lambda x: x.hour) < 20)).astype(int)
df['Night'] = ((df['Time'].apply(lambda x: x.hour) >= 20) | (df['Time'].apply(lambda x: x.hour) < 6)).astype(int)

# Combine morning, afternoon, and night into a single column 'Time-Day'
def classify_time(row):
    if row['Morning'] == 1:
        return 'Morning'
    elif row['Afternoon'] == 1:
        return 'Afternoon'
    elif row['Night'] == 1:
        return 'Night'
    else:
        return None

df['Time-Day'] = df.apply(classify_time, axis=1)

# Display the updated DataFrame
selected_columns = ['rDate', 'Month', 'Year','Weekday','Time','Time-Day','Morning','Afternoon','Night',
                    'Sender','clean_msg','emoji','word_count_group']
df = df[selected_columns]
df.head()

,rDate,Month,Year,Weekday,Time,Time-Day,Morning,Afternoon,Night,Sender,clean_msg,emoji,word_count_group
2,2021-02-02,2,2021,Tuesday,04:05:00,Night,0,0,1,Eze,(risa),ü§¶,short msg
5,2021-02-02,2,2021,Tuesday,04:34:00,Night,0,0,1,Barde,(risa),_,short msg
6,2021-02-02,2,2021,Tuesday,07:25:00,Morning,1,0,0,Juan,finoli finoli,_,short msg
7,2021-02-02,2,2021,Tuesday,07:25:00,Morning,1,0,0,Juan,tiene una amonestaci√≥n colectiva schames,_,short msg
11,2021-02-02,2,2021,Tuesday,12:41:00,Morning,1,0,0,Matias,me gust√≥ eso,_,short msg

In [36]:
data = df[df['Year']== 2023]
data.shape

(9770, 13)

In [37]:
# Assuming `data` is your DataFrame containing the filtered data
data.to_csv('data.csv', index=False)